<?php


/**
 * Is the current admin page generated by a plugin?
 *
 * Use global $plugin_page and/or get_plugin_page_hookname() hooks.
 *
 * @since 1.5.0
 * @deprecated 3.1.0
 *
 * @global $plugin_page
 *
 * @return bool
 */
function is_plugin_page()
{
}